### PR TITLE
Added ClientTxnAsync class that executes ClientTransaction asynchrono…

### PR DESCRIPTION
**Pull request by mehturt**
...usly.

Execute transaction from Register asynchronously.

### CODE REVIEW

**Comment by atsakiridis** [comment]
Great job mehturt and welcome to the mobicents community :) 

Could you please drop by:

http://www.telestax.com/open-source/#Contribute

and fill in the contributor form?

Thanks!

**Comment by atsakiridis** [comment]
mehturt, but I'm gonna need a little time to to merge those because I'm in the middle of changing a lot of sources at the moment and want to make sure I don't break anything. Will let you know when ready

**Comment by mehturt** [comment]
Thanks, no worries.

**Comment by atsakiridis** [comment]
@mehturt I had a better look at your commits, please check my comments. Thanks!

**Comment by atsakiridis** [comment]
@mehturt I finally found time to add the fixes for the async issue as discussed. On the advanced settings if you are still interested in adding them, please do a rebase as the source code has changed considerably

Best regards,
Antonis

**Comment by atsakiridis** [comment]
I'm closing this as I believe that the advanced setting part is delivered with https://github.com/RestComm/restcomm-android-sdk/pull/283, which I plan to review soon. Please let me know if I'm missing something @mehturt

**Comment by mehturt** [comment]
Yes, I've started from scratch on the recent code base.

**Pull request closed without merging**
