### PR TITLE
Handling of port as part of domain

### PR DESCRIPTION
**Pull request by mehturt**
Can we separate the port from the domain in preferences?

### CODE REVIEW

**Comment by atsakiridis** [comment]
I would like to avoid to do that @mehturt as it's how we do it on all Restcomm SDKs. What is the problem?

**Comment by mehturt** [comment]
@atsakiridis  Ok, so I need to understand what is the problem. If one specifies a domain with port, e.g. "restcomm.xyz:1234" the application should connect to port 1234 and does not do so now? Or the problem only happens when the proxy is specified, but the port is in the domain rather than in the proxy configuration? Or something else?
Thanks.

**Comment by atsakiridis** [comment]
@mehturt, the issue is when one specifies a domain with port (like sip:192.168.2.1:5080). In that case the application breaks at:

https://github.com/mehturt/restcomm-android-sdk/blob/10ed8d42f3d9e2a0052ff995a2d3be0bc7fa9089/restcomm.android.client.sdk/src/main/java/org/mobicents/restcomm/android/sipua/impl/sipmessages/Register.java#L37 

With 'Error parsing SIP URI' because it only needs the ip part, but instead it get's the whole domain. You can try it your self. Build your App (with your changes) and use a full domain like the one I have above. It should break for the same reason

**Comment by atsakiridis** [comment]
Closing this due to lack of activity. Feel free to reopen

**Pull request closed without merging**
